/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_appsync_graphqlEndpoint": "https://om3iunsjsra2lgzrpf7dfvqou4.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gz3feergkjdwbebuuh2atbicqu",
    "aws_cloud_logic_custom": [
        {
            "name": "jobs",
            "endpoint": "https://tiwfzro0ja.execute-api.ap-northeast-2.amazonaws.com/staging",
            "region": "ap-northeast-2"
        }
    ]
};


export default awsmobile;
